#+ summary: Find begreber og deres skemaa (skos:ConceptScheme instansen samt samt skos:Concepts som er inScheme et givet ConceptScheme (brug ?schemeuri=URI)
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT WHERE
{?_schemeuri_iri rdf:type skos:ConceptScheme .
	OPTIONAL {?_schemeuri_iri skos:prefLabel ?prefLabel}
	OPTIONAL {?_schemeuri_iri skos:altLabel ?altLabel}
	OPTIONAL {?_schemeuri_iri skos:definition ?definition}
	OPTIONAL {?_schemeuri_iri skos:example ?example}
	OPTIONAL {?_schemeuri_iri skos:hiddenLabel ?hiddenLabel}
	OPTIONAL {?_schemeuri_iri skos:changeNote ?changeNote}
	OPTIONAL {?_schemeuri_iri skos:editorialNote ?editorialNote}
	OPTIONAL {?_schemeuri_iri skos:hasTopConcept ?hasTopConcept}
	OPTIONAL {?_schemeuri_iri rdf:type  ?type} 
}
