#+ summary: Find begreber og deres skemaa (skos:ConceptScheme instansen samt samt skos:Concepts som er inScheme et givet ConceptScheme (brug ?schemeuri=URI)
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT 
	{	
	?_schemeuri_iri rdf:type  ?type . 
?_schemeuri_iri skos:prefLabel ?prefLabel .
?_schemeuri_iri skos:altLabel ?altLabel .
?_schemeuri_iri skos:definition ?definition .
?_schemeuri_iri skos:example ?example .
?_schemeuri_iri skos:hiddenLabel ?hiddenLabel .
?_schemeuri_iri skos:changeNote ?changeNote .
?_schemeuri_iri skos:hasTopConcept ?hasTopConcept .
?_schemeuri_iri skos:editorialNote ?editorialNote 
		}
	WHERE
{?_schemeuri_iri rdf:type skos:ConceptScheme .
	OPTIONAL {?_schemeuri_iri skos:prefLabel ?prefLabel}
	OPTIONAL {?_schemeuri_iri skos:altLabel ?altLabel}
	OPTIONAL {?_schemeuri_iri skos:definition ?definition}
	OPTIONAL {?_schemeuri_iri skos:example ?example}
	OPTIONAL {?_schemeuri_iri skos:hiddenLabel ?hiddenLabel}
	OPTIONAL {?_schemeuri_iri skos:changeNote ?changeNote}
	OPTIONAL {?_schemeuri_iri skos:editorialNote ?editorialNote}
	OPTIONAL {?_schemeuri_iri skos:hasTopConcept ?hasTopConcept}
	OPTIONAL {?_schemeuri_iri rdf:type  ?type} 
}
CONSTRUCT 
	{
?noget rdf:type  ?type . 
?noget skos:inScheme ?skema .
?noget skos:prefLabel ?prefLabel .
?noget skos:altLabel ?altLabel .
?noget skos:definition ?definition .
?noget skos:example ?example .
?noget skos:hiddenLabel ?hiddenLabel .
?noget skos:changeNote ?changeNote .
?noget skos:editorialNote ?editorialNote .
?noget skos:topConceptOf ?topConceptOf .
?noget skos:related ?related .
?noget skos:narrower ?narrover .
?noget skos:broader ?broader .
?noget skos:relatedMatch ?relatedMatch .
?noget skos:closeMatch ?closeMatch .
?noget skos:exactMatch ?exactMatch .
?noget skos:broaderMatch ?broaderMatch .
?noget skos:narrowerMatch ?narrowerMatch }
WHERE 
{?noget skos:inScheme ?_schemeuri_iri.
OPTIONAL {?noget skos:prefLabel ?prefLabel}
OPTIONAL {?noget skos:altLabel ?altLabel}
OPTIONAL {?noget skos:definition ?definition}
OPTIONAL {?noget skos:example ?example}
OPTIONAL {?noget skos:hiddenLabel ?hiddenLabel}
OPTIONAL {?noget skos:changeNote ?changeNote}
OPTIONAL {?noget skos:editorialNote ?editorialNote}
OPTIONAL {?noget skos:topConceptOf ?topConceptOf}
OPTIONAL {?noget skos:related ?related}
OPTIONAL {?noget skos:narrower ?narrover}
OPTIONAL {?noget skos:broader ?broader}
OPTIONAL {?noget skos:relatedMatch ?relatedMatch}
OPTIONAL {?noget skos:closeMatch ?closeMatch}
OPTIONAL {?noget skos:exactMatch ?exactMatch}
OPTIONAL {?noget skos:broaderMatch ?broaderMatch}
OPTIONAL {?noget skos:narrowerMatch ?narrowerMatch}
OPTIONAL {?noget skos:inScheme ?skema}
OPTIONAL {?noget rdf:type  ?type} 
}



