#+ summary: Find alle klassifikationer på serveren - i dette tilfælde alle skos:ConceptScheme		

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT {?noget rdf:type  ?type . 
       ?noget skos:prefLabel ?prefLabel .
       ?noget skos:altLabel ?altLabel .
       ?noget skos:definition ?definition .
       ?noget skos:example ?example .
       ?noget skos:hiddenLabel ?hiddenLabel .
       ?noget skos:changeNote ?changeNote .
       ?noget skos:editorialNote ?editorialNote .
       ?noget skos:hasTopConcept ?topConcept
}
WHERE {?noget rdf:type skos:ConceptScheme .
       OPTIONAL {?noget skos:prefLabel ?prefLabel}
       OPTIONAL {?noget skos:altLabel ?altLabel}
       OPTIONAL {?noget skos:definition ?definition}
       OPTIONAL {?noget skos:example ?example}
       OPTIONAL {?noget skos:hiddenLabel ?hiddenLabel}
       OPTIONAL {?noget skos:changeNote ?changeNote}
       OPTIONAL {?noget skos:editorialNote ?editorialNote}
       OPTIONAL {?noget rdf:type  ?type} 
       OPTIONAL {?noget skos:hasTopConcept ?topConcept}
}
