#+ summary: Hent begreb (skos:Concept) med en givn URI (brug ?concepturi=URI)

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {?_concepturi_iri rdf:type  ?type . 
	?_concepturi_iri skos:inScheme ?skema .
	?_concepturi_iri skos:prefLabel ?prefLabel .
	?_concepturi_iri skos:altLabel ?altLabel .
	?_concepturi_iri skos:definition ?definition .
	?_concepturi_iri skos:example ?example .
	?_concepturi_iri skos:hiddenLabel ?hiddenLabel .
	?_concepturi_iri skos:changeNote ?changeNote .
	?_concepturi_iri skos:editorialNote ?editorialNote .
	?_concepturi_iri skos:topConceptOf ?topConceptOf .
	?_concepturi_iri skos:related ?related .
	?_concepturi_iri skos:narrower ?narrover .
	?_concepturi_iri skos:broader ?broader .
	?_concepturi_iri skos:relatedMatch ?relatedMatch .
	?_concepturi_iri skos:closeMatch ?closeMatch .
	?_concepturi_iri skos:exactMatch ?exactMatch .
	?_concepturi_iri skos:broaderMatch ?broaderMatch .
	?_concepturi_iri skos:narrowerMatch ?narrowerMatch}
WHERE {?_concepturi_iri rdf:type skos:Concept .
	OPTIONAL {?_concepturi_iri skos:prefLabel ?prefLabel}
	OPTIONAL {?_concepturi_iri skos:altLabel ?altLabel}
	OPTIONAL {?_concepturi_iri skos:definition ?definition}
	OPTIONAL {?_concepturi_iri skos:example ?example}
	OPTIONAL {?_concepturi_iri skos:hiddenLabel ?hiddenLabel}
	OPTIONAL {?_concepturi_iri skos:changeNote ?changeNote}
	OPTIONAL {?_concepturi_iri skos:editorialNote ?editorialNote}
	OPTIONAL {?_concepturi_iri skos:topConceptOf ?topConceptOf}
	OPTIONAL {?_concepturi_iri skos:related ?related}
	OPTIONAL {?_concepturi_iri skos:narrower ?narrover}
	OPTIONAL {?_concepturi_iri skos:broader ?broader}
	OPTIONAL {?_concepturi_iri skos:relatedMatch ?relatedMatch}
	OPTIONAL {?_concepturi_iri skos:closeMatch ?closeMatch}
	OPTIONAL {?_concepturi_iri skos:exactMatch ?exactMatch}
	OPTIONAL {?_concepturi_iri skos:broaderMatch ?broaderMatch}
	OPTIONAL {?_concepturi_iri skos:narrowerMatch ?narrowerMatch}
	OPTIONAL {?_concepturi_iri skos:inScheme ?skema}
	OPTIONAL {?_concepturi_iri rdf:type  ?type} 
}
