#+ summary: Hent begrebssystem (skos:ConceptScheme) med en givn URI (brug ?schemeuri=URI)
#+ tags:		
#+   - SPARQL		
#+   - SKOS
#+ enumerate:		
#+   - schemeuri		
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT {?_schemeuri_iri rdf:type  ?type . 
	?_schemeuri_iri skos:prefLabel ?prefLabel .
	?_schemeuri_iri skos:altLabel ?altLabel .
	?_schemeuri_iri skos:definition ?definition .
	?_schemeuri_iri skos:example ?example .
	?_schemeuri_iri skos:hiddenLabel ?hiddenLabel .
	?_schemeuri_iri skos:changeNote ?changeNote .
	?_schemeuri_iri skos:hasTopConcept ?hasTopConcept .
	?_schemeuri_iri skos:editorialNote ?editorialNote 
	}
WHERE {?_schemeuri_iri rdf:type skos:ConceptScheme .
	OPTIONAL {?_schemeuri_iri skos:prefLabel ?prefLabel}
	OPTIONAL {?_schemeuri_iri skos:altLabel ?altLabel}
	OPTIONAL {?_schemeuri_iri skos:definition ?definition}
	OPTIONAL {?_schemeuri_iri skos:example ?example}
	OPTIONAL {?_schemeuri_iri skos:hiddenLabel ?hiddenLabel}
	OPTIONAL {?_schemeuri_iri skos:changeNote ?changeNote}
	OPTIONAL {?_schemeuri_iri skos:editorialNote ?editorialNote}
	OPTIONAL {?_schemeuri_iri skos:hasTopConcept ?hasTopConcept}
	OPTIONAL {?_schemeuri_iri rdf:type  ?type} 
}
