#+ summary: Hent begreb (skos:Concept) med en givn URI (brug ?concepturi=URI)
#+ tags:		
#+   - SPARQL		
#+   - SKOS
#+ enumerate:		
#+   - concepturi		

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
CONSTRUCT WHERE {?_concepturi_iri rdf:type skos:Concept}
	
